### ISSUE TITLE
Fix schema validation for yaml files

### ISSUE THREAD

**Issue by nschcolnicov** [nextflow-io/nf-schema#79]
Trying to use the following incorrect schema file:
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/schemas/schema_contrasts.json",
    "title": "nf-core/differentialabundance pipeline - params.contrasts schema",
    "description": "Schema for the file provided with params.contrasts",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "contrasts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                "id": {
                    "type": "string"
                },
                "comparison": {
                    "type": "array",
                    "items": {
                    "type": "string"
                    },
                    "minItems": 1
                },
                "blocking_factors": {
                    "type": "array",
                    "items": {
                    "type": "string"
                    },
                    "minItems": 1
                }
                },
                "required": ["id", "comparison"],
                "additionalProperties": false
            },
            "minItems": 1
            }
        },
        "required": ["contrasts"],
        "additionalProperties": false
        }
}
```

On this .yaml file:
```
contrasts:
  - id: treatment_mCherry_hND6_
    comparison: ["treatment", "mCherry", "hND6"]
  - id: treatment_mCherry_hND6_sample_number
    comparison: ["treatment", "mCherry", "hND6"]
    blocking_factors: ["sample_number"]
```

Raises this error:
```
ERROR ~ Cannot cast object '{contrasts=[{id=treatment_mCherry_hND6_, comparison=[treatment, mCherry, hND6]}, {id=treatment_mCherry_hND6_sample_number, comparison=[treatment, mCherry, hND6], blocking_factors=[sample_number]}]}' with class 'java.util.LinkedHashMap' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(LinkedHashMap)
```

The issue seems to be that schema doesn't match the file, but the error could be improved to display how is it not matching and why.
FYI @nvnieuwk 

```[tasklist]
### Tasks
- [ ] Improve error message
- [ ] Fix schema validation
```

**Comment by nschcolnicov** [comment]
A second issue was found, when passing the correct schema:
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/schemas/schema_contrasts.json",
    "title": "nf-core/differentialabundance pipeline - params.contrasts schema",
    "description": "Schema for the file provided with params.contrasts",
        "type": "object",
        "properties": {
            "contrasts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                "id": {
                    "type": "string"
                },
                "comparison": {
                    "type": "array",
                    "items": {
                    "type": "string"
                    },
                    "minItems": 1
                },
                "blocking_factors": {
                    "type": "array",
                    "items": {
                    "type": "string"
                    },
                    "minItems": 1
                }
                },
                "required": ["id", "comparison"],
                "additionalProperties": false
            },
            "minItems": 1
            }
        },
        "required": ["contrasts"],
        "additionalProperties": false
}
```
This error is raised:
```
ERROR ~ Cannot get property 'properties' on null object
```
FYI @nvnieuwk

**Comment by nvnieuwk** [comment]
Note to self: this is because the schema expects a map, but gets a list

After fixing this another issue occured:
```
java.lang.NullPointerException: Cannot get property 'properties' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:92)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:167)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:424)
	at org.codehaus.groovy.runtime.dgm$325.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:233)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:75)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.validation.Utils.variableTypes(Utils.groovy:144)
	at nextflow.validation.Utils$variableTypes$3.callStatic(Unknown Source)
	at nextflow.validation.Utils.fileToList(Utils.groovy:58)
	at nextflow.validation.Utils$fileToList$1.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at nextflow.validation.Utils$fileToList$1.callStatic(Unknown Source)
	at nextflow.validation.Utils.fileToJsonArray(Utils.groovy:91)
	at nextflow.validation.Utils$fileToJsonArray$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at nextflow.validation.Utils$fileToJsonArray$0.call(Unknown Source)
	at nextflow.validation.SchemaEvaluator.evaluate(SchemaEvaluator.groovy:53)
	at dev.harrel.jsonschema.EvaluatorWrapper.evaluate(EvaluatorWrapper.java:23)
	at dev.harrel.jsonschema.EvaluationContext.lambda$validateAgainstSchema$12(EvaluationContext.java:168)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667)
	at dev.harrel.jsonschema.EvaluationContext.validateAgainstSchema(EvaluationContext.java:164)
	at dev.harrel.jsonschema.EvaluationContext.lambda$resolveInternalRefAndValidate$6(EvaluationContext.java:115)
	at java.base/java.util.Optional.map(Optional.java:260)
	at dev.harrel.jsonschema.EvaluationContext.resolveInternalRefAndValidate(EvaluationContext.java:115)
	at dev.harrel.jsonschema.PropertiesEvaluator.evaluate(Applicators.java:279)
	at dev.harrel.jsonschema.EvaluatorWrapper.evaluate(EvaluatorWrapper.java:23)
	at dev.harrel.jsonschema.EvaluationContext.lambda$validateAgainstSchema$12(EvaluationContext.java:168)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667)
	at dev.harrel.jsonschema.EvaluationContext.validateAgainstSchema(EvaluationContext.java:164)
	at dev.harrel.jsonschema.EvaluationContext.validateAgainstRefSchema(EvaluationContext.java:193)
	at dev.harrel.jsonschema.EvaluationContext.lambda$resolveRefAndValidate$0(EvaluationContext.java:58)
	at java.base/java.util.Optional.map(Optional.java:260)
	at dev.harrel.jsonschema.EvaluationContext.resolveRefAndValidate(EvaluationContext.java:58)
	at dev.harrel.jsonschema.RefEvaluator.evaluate(Applicators.java:632)
	at dev.harrel.jsonschema.EvaluatorWrapper.evaluate(EvaluatorWrapper.java:23)
	at dev.harrel.jsonschema.EvaluationContext.lambda$validateAgainstSchema$12(EvaluationContext.java:168)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667)
	at dev.harrel.jsonschema.EvaluationContext.validateAgainstSchema(EvaluationContext.java:164)
	at dev.harrel.jsonschema.EvaluationContext.lambda$resolveInternalRefAndValidate$6(EvaluationContext.java:115)
	at java.base/java.util.Optional.map(Optional.java:260)
	at dev.harrel.jsonschema.EvaluationContext.resolveInternalRefAndValidate(EvaluationContext.java:115)
	at dev.harrel.jsonschema.AllOfEvaluator.evaluate(Applicators.java:448)
	at dev.harrel.jsonschema.EvaluatorWrapper.evaluate(EvaluatorWrapper.java:23)
	at dev.harrel.jsonschema.EvaluationContext.lambda$validateAgainstSchema$12(EvaluationContext.java:168)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667)
	at dev.harrel.jsonschema.EvaluationContext.validateAgainstSchema(EvaluationContext.java:164)
	at dev.harrel.jsonschema.Validator.validate(Validator.java:145)
	at dev.harrel.jsonschema.ValidatorFactory.validate(ValidatorFactory.java:231)
	at dev.harrel.jsonschema.ValidatorFactory.validate(ValidatorFactory.java:214)
	at nextflow.validation.JsonSchemaValidator.validateObject(JsonSchemaValidator.groovy:51)
	at nextflow.validation.JsonSchemaValidator.validate(JsonSchemaValidator.groovy:113)
	at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy:331)
	at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at nextflow.script.FunctionDef.invoke_a(FunctionDef.groovy:64)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:651)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:330)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at Script_215a636da7ab24a2$_runScript_closure1$_closure2.doCall(Script_215a636da7ab24a2:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:412)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:651)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:330)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at Script_e8e0bb4fa8a9a3ef$_runScript_closure3$_closure5.doCall(Script_e8e0bb4fa8a9a3ef:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:412)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:651)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:330)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at Script_5544e1ace25b58ab$_runScript_closure2$_closure4.doCall(Script_5544e1ace25b58ab:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:412)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:198)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.script.BaseScript.run(BaseScript.groovy:209)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:236)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:243)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:138)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:376)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:658)
```

**Comment by nvnieuwk** [comment]
This has been fixed and will be available in the soon to be released 2.3.0 version :)
